### ISSUE TITLE
Sample scene needs to be added?

### ISSUE THREAD

**Issue by littleggghost** [robot-locomotion/dwl#6]
Hi, @cmastalli  
You did a really marvelous job with DWL, it accomplish so many works and seems very professional.
But I can't run it with ROS because I even do not have a .launch file to start a sample scene. I have install so many dependencies, such as terrain-server, dwl, dwl-msgs, dwl-rviz-plugin, hyq_description and don't know how to start learning it now.
Maybe you can give me some help? Thanks in advance!

**Comment by littleggghost** [comment]
Could you add a scene like the .gif shows in home page?

**Comment by cmastalli** [comment]
Thank you for your feedback!

I'm not sure what you would like to try? Probably the terrain-server? If so, you can use one of the launch files inside terrain-server to build a synthetic map (e.g. stepping_stones.launch).

If you're interesting in the whole-body publisher (i.e. dwl-rviz-plugin). What you can do is to plug this pulisher (ROS control publisher) along your robot and then display in RVIZ. The whole-body publisher is tailored to quadruped robots, however it's not a big deal to integrating in other kind robots; you just need to publish a dwl_msg::WholeBodyState message.

Is this answer your concerns?

**Comment by littleggghost** [comment]
Thanks for your rapidly reply!
Well, I would like to have a tutorial step by step. 
For example, in order to achieve the following effect:
![68747470733a2f2f692e696d6775722e636f6d2f545572676b7a4f2e676966](https://user-images.githubusercontent.com/5058791/55408348-6afc0c00-5592-11e9-890a-8ecd4e43b39b.gif)
Then:
1. install the necessary tools, like xxx;
2. run catkin_make
3. roslaunch xxx xxx.launch
4. rosrun xxx xxx

I know what the plugin means, but I would like to try it first. If someone have never use something before, then dirty his hands is the best way to teach and learn.
I think that would be a great help to get familiar with DWL.

**Comment by littleggghost** [comment]
As your suggest, I try to launch stepping_stones.launch and nothing happens, because it did't launch the rviz node. 
Here the question is, all the parts are already have, how to let them work together. Could you understand the doubts of a beginner?

**Comment by cmastalli** [comment]
The gif shows you how to display whole-body states inside RVIZ. For doing so, these are general instructions
1. You need to install dwl, dwl_msgs, dwl_rviz_plugin and wb_state_publisher. You can do so by adding all of them inside your catkin workspace.
2. You have to launch HyQ with default a gazebo controller along the with wb_state_publisher. This guys is a ros controller which only publish dwl::WholeBodyState data (similarly to the ROS joint state publisher).
3. You have to launch RVIZ and to add the dwl::WholeBodyState plugin. Remember that you need to publish the TF as usually is done in ROS.

The trotting controller that you see in that video (or other walking controllers) are closed source. DWL doesn't include any of them, just facilities to develop your own controller.

---
The stepping_stones launch file generates a synthetic point cloud. Then from it, you can compute the terrain costmap. This is done by building terrain_server with catkin system. Finally you have to run the terrain server by launching terrain_server.launch.

Displaying the terrain costmap can be done through RVIZ. You just need the plugin defined in dwl_rviz_plugin.

**Comment by littleggghost** [comment]
Thanks for your patience.
I have finished step 1, but step 2 and 3 seems not given in dwl related repositories. It seems needs to be achieve by user himself.
And, even if the trotting controller is closed source, you can also provide some .bag files that easy to get started.

**Comment by EricWang1hitsz** [comment]
> Thanks for your patience.
> I have finished step 1, but step 2 and 3 seems not given in dwl related repositories. It seems needs to be achieve by user himself.
> And, even if the trotting controller is closed source, you can also provide some .bag files that easy to get started.

Did you have some problems when you installed the dwl package?

**Comment by littleggghost** [comment]
May be some packages are not exist. You can comment them.

**Comment by EricWang1hitsz** [comment]
> May be some packages are not exist. You can comment them.

But when I installed the dwl package, I had the following problems.

![image](https://user-images.githubusercontent.com/45548007/65398960-b4fcd680-ddec-11e9-9a7b-0c0c813cfe13.png)

Did you have the same problem?

**Comment by littleggghost** [comment]
I didn't get this error. Maybe the **yaml** or **dwl** it self has an error.

**Comment by cmastalli** [comment]
You didn't install the share library of yaml-cpp, only the static one.

If you use the installation script, everything should be smoother: https://github.com/robot-locomotion/dwl/blob/master/install_deps.sh

**Comment by cmastalli** [comment]
Feel free to reopen this issue
