### ISSUE TITLE
Error when making install

### ISSUE THREAD

**Issue by EricWang1hitsz** [robot-locomotion/dwl#7]
Hello, 

Thanks for your contribution and you did a great job!  When I installed the "dwl", I met the following problem:
 

![image](https://user-images.githubusercontent.com/45548007/65340503-f29d0c00-dc00-11e9-8c48-f0ff28cac158.png)

Could u tell me how to solve the problem?  

Thank you very much!

**Comment by EricWang1hitsz** [comment]
@cmastalli

**Comment by cmastalli** [comment]
The API of RBDL has been changed, do you mind to solve this tiny issue?

For more details see:
https://rbdl.bitbucket.io/df/d72/namespace_rigid_body_dynamics_1_1_utils.html

**Comment by EricWang1hitsz** [comment]
Thank you very much for your reply! 
Yes, I tried. I successfully installed the dwl package, but when I catkin make the terrain-server and dwl-msg package, I had a new problem. I set the path of the dwl in cmakelist,  but I don't know why it cannot link to the .so file?  

![image](https://user-images.githubusercontent.com/45548007/65411856-87318500-de20-11e9-932c-2868f24462aa.png)

**Comment by cmastalli** [comment]
You cannot link the **dwl** library. You have to double check if you define `LD_LIBRARY_PATH ` properly. Alternatively, you can also compile **dwl** using catkin.

**Comment by EricWang1hitsz** [comment]
I have finished building all three packages. Thanks a lot for your patient answers!

**Comment by cmastalli** [comment]
You're welcome
